### ISSUE TITLE
customSelect() is triggering onChange event on select list item

### ISSUE THREAD

**Issue by simakas** [adamcoulombe/jquery.customSelect#13]
customSelect() is triggering onChange event on select list item, page goes into infinite loop.
![example behaviour](https://f.cloud.github.com/assets/3416239/106705/0fe35160-6a08-11e2-9c37-ed6b13ab84a7.gif)

**Comment by adamcoulombe** [comment]
Hey I need more details one whats happening here. The screenshot you posted is tiny and I cant see anything. Better yet, if you have a fix for it put in a pull request.

**Comment by simakas** [comment]
hey,

dont have a fix, maybe you could explain where the "change" function is
fired in your source?
test case:
- select list has <onChange="doSubmit('FIND');">. it submits the page with
  some details on change
- the line $this.change(); (line 27) is triggering the event and page loads
  infinitely
- tried to play by replacing change with input or some custom functions,
  but failed..  not completely sure what connected where there.

Simon

On Tue, Jan 29, 2013 at 3:24 PM, Adam Coulombe notifications@github.comwrote:

> Hey I need more details one whats happening here. The screenshot you
> posted is tiny and I cant see anything. Better yet, if you have a fix for
> it put in a pull request.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/adamcoulombe/jquery.customSelect/issues/13#issuecomment-12834164.

## 

simakas@gmail.com
simonas@awsys.no
+370 699 66435

**Comment by adamcoulombe** [comment]
ah, I see what you mean. The plugin fires the change event to initiate the anonymous function that is attached to the change event on line 33... The solution is to give the anonymous function a proper function name and call it directly on line 27 instead of firing the change event.

**Comment by adamcoulombe** [comment]
Latest version should fix this issue now that the change callback has been moved to a named function

**Comment by simakas** [comment]
works like a charm. thank you!
