### ISSUE TITLE
customSelect Doesn't "Close" When You Click Elsewhere

### ISSUE THREAD

**Issue by ericrovtar** [adamcoulombe/jquery.customSelect#14]
If you click on the customSelect box and it opens and then click on an area of the page other than the customSelect or options box, the options box closes, but customSelect retains the customSelectOpen class.

Looking at the code, it's because the only way to remove the customSelectOpen class is for the customSelect to lose focus and "blur," but since the customSelect still has focus, it's retaining the customSelectOpen class.

I guess the issue is what event do you look for, then?

I'd gladly amend the script myself, but wonder what the best solution is.

Thanks!

**Comment by adamcoulombe** [comment]
customSelectOpen should also go away when select value changes (see [line 161 of jquery.customselect.js](https://github.com/adamcoulombe/jquery.customSelect/blob/35ab9c3c9886a62bca324bd4fc7b07d21e994022/customSelect.jquery.js#L61)). There was also a logic update to how this class behaves that may have fixed your issue? 35ab9c3c9886a62bca324bd4fc7b07d21e994022 . If you are still having the issue, can you please post an example to show what you mean?
