### ISSUE TITLE
Responsive

### ISSUE THREAD

**Issue by nathan-isaac** [adamcoulombe/jquery.customSelect#16]
Hello, I have noticed when using this plugin in a responsive design the width of the select and span are static relative to the width of the browser upon refresh. Is there a way to make it have a dynamic width? 

I can make it dynamic when I go into the browser and inspect the element. I change both the width of the span.customSelectInner and the select to 100%. 

Thanks.

**Comment by adamcoulombe** [comment]
If youre trying do do a percentage based width, you may have a hard time using this plugin in a reasonable way. If you just want it responsive to media queries you can always use something like matchmedia or enquire.js like so: http://bit.ly/12skNKS

**Comment by adamcoulombe** [comment]
I guess you could also trigger customselect update on the on the window resize event but you'll have to calculate the width manually with js. Not a pretty solution but it would work.
