### ISSUE TITLE
Select height problem

### ISSUE THREAD

**Issue by felipers** [adamcoulombe/jquery.customSelect#20]
It seems that the hidden select does not get the correct height on this line:

``` js
var selectBoxHeight = customSelectSpan.outerHeight();
```

Version 0.2.4 seems ok.

**Comment by adamcoulombe** [comment]
can you post a jsfiddle example so I can see exactly whats happening

**Comment by stevendierick** [comment]
Idd, this still works in v0.2.4.

Here's a jsFiddle: http://jsfiddle.net/Exayle/gtH43/

**Comment by RoryH** [comment]
Seeing the same problem in Chrome 25.0.1364.99, bizarrely though it seems to work for some of my select boxes. I have 4 seelct boxes on the page, and 2 of them (the last 2) have this problem

**Comment by adamcoulombe** [comment]
Thx gang. Some code that was consolidated for 0.3.0 broke the order of things. Just pushed an update and should be good to go again with the 0.3.2 update. Please get the latest version and consider the old version faulty
