### ISSUE TITLE
.value= does not change dropDowns text

### ISSUE THREAD

**Issue by simakas** [adamcoulombe/jquery.customSelect#22]
hi,

when setting a value in JS for customSelect dropdown, just only selectedIndex is changed, not displayed value:

document.getElementById("P107_EDIT_VATID").value = 117;

selectedIndex does return value correctly, but not visible in the dropdown, until you drop it.

alert(document.getElementById("P107_EDIT_VATID").options[document.getElementById("P107_EDIT_VATID").selectedIndex].value);

**Comment by adamcoulombe** [comment]
if you are setting the select value programatically, you need to trigger an update:

``` javascript
var $cs = $("#P107_EDIT_VATID").customSelect();

$cs.val(117).trigger('update');
```

**Comment by simakas** [comment]
in my case its a place where values are loaded into drops and they already have customSelect assigned in page header.
quite a nasty workaround to get display value populated...

```
var dd = document.getElementById("P107_EDIT_VATID");  // item
readXML(ret, "VAT", "P107_EDIT_VATID");                      // procedure populating item value (could be static)
var $cs = $("#P107_EDIT_VATID");                                //.customSelect() is already present
try
  {$cs.val(dd.options[dd.selectedIndex].value).trigger('update');  // updating value based on selected index
  }
catch(e)
  {dd.value = '0';                                                    // if value was not set, set it to your null/default value..
   $cs.val('< Choose something >').trigger('update');  //...null/default dropdown text value
  }
```

**Comment by adamcoulombe** [comment]
your `dd` variable is the same as `$cs[0]`, so you have a lot of redundance here. If you are populating the dropdown using readXML, the select value will be set already. So all you should need to do is trigger an update. If you actually are loading XML this needs to happen in the callback otherwise you will fire the update way before the values are actually loaded.

``` javascript
readXML(ret, "VAT", "P107_EDIT_VATID");  
```

after readXML is successful...

``` javascript
// $cs.val() == dd.value - no need to maintain two different vars
var newVal = $cs.val() || '< Choose something >';
$cs.val(newVal).trigger('update');
```

**Comment by simakas** [comment]
yeap, way less overhead, just had to add 'return value', not 'display value' for it to work.

```
readXML(ret, "VAT", "P107_EDIT_VATID");  // populate dropdown item
var $cs = $("#P107_EDIT_VATID");             // issue variable
var newVal = $cs.val() || '0';                         // option set + default return value (or text as suggested above)
$cs.val(newVal).trigger('update');                 // trigger an update
```

**Comment by teambalthazar** [comment]
Might be worth updating the answers in here to `.trigger('render');` instead of `.trigger('update)` for any googlers (like me) who might find their way here. I assume this is something that has changed in the plugin over the last 2 years as update didn't work for me, but render did.

**Comment by MuhammadFaizanKhan** [comment]
I have used these two method but still i am failed to select dropdown option using code.
```
  var mainProjectDropdown = $jq("#mainProjectId").customselect();
            mainProjectDropdown.val(mainProjectId).trigger('render');
```
 The second way:
```
  var mainProjectDropdown = $jq("#mainProjectId").customselect();
  mainProjectDropdown.val(mainProjectId).trigger('update');
```
