### ISSUE TITLE
Does not work for multiple select tags if they are floated

### ISSUE THREAD

**Issue by defsprite** [adamcoulombe/jquery.customSelect#23]
Adding a simple `float:left` to the select elements completely breaks the interaction on all but the first `select` elements.

**Comment by adamcoulombe** [comment]
It's possible float may disrupt the positioning. Right now the customSelect span gets injected as the next sibling of the select box. The select box itself is given `position:absolute` and sits on top of the span as an invisible element. So applying `float:left` to the select box may give some mixed results. I would suggest considering wrapping a `<label>` or something around it and floating that instead, that way you know what you are getting...

**Comment by adamcoulombe** [comment]
http://jsfiddle.net/adamco/z2Eey/
