### ISSUE TITLE
applying custom select to new select

### ISSUE THREAD

**Issue by loicbar** [adamcoulombe/jquery.customSelect#25]
Apparently, the script doesn't work when you create via jQuery a new select and then you try to apply the customSelect.

**Comment by adamcoulombe** [comment]
javascript cannot calculate the actual height, width, font-size, etc (`getComputedStyle`/`.css()` ) until the element has been added to the dom. Hence customSelect will not work properly. Make sure you append it first, then do customSelect.

example http://jsfiddle.net/adamco/3TsKq/
