### ISSUE TITLE
JS open event

### ISSUE THREAD

**Issue by ghost** [adamcoulombe/jquery.customSelect#27]
How to open the select element via JavaScript ?

**Comment by adamcoulombe** [comment]
`customSelect` uses native browser select boxes which cannot be opened via javascript. see http://stackoverflow.com/questions/4457076/show-select-dropdown-in-jquery

as noted in that discussion, the only way to fake this is by building your own select. Ie, using a plugin like https://github.com/gfranko/jquery.selectBoxIt.js or the like

**Comment by ghost** [comment]
Okay, thank you anyway for the link
