### ISSUE TITLE
Dynamically Populated Custom Select

### ISSUE THREAD

**Issue by netpoetica** [adamcoulombe/jquery.customSelect#28]
How do you make this plugin work in a situation where you use AJAX to repopulate a select list's options after you've already called .customSelect() on that same select element before?

**Comment by adamcoulombe** [comment]
Hey Keith...

Populate the select as usual then call $('#myselect').trigger('update');

**Comment by netpoetica** [comment]
@adamcoulombe thank you for clarifying this

**Comment by snow-walker** [comment]
$('#myselect').trigger('update'); did the trick for me. Thanks.
