### ISSUE TITLE
select in hidden DIVs

### ISSUE THREAD

**Issue by kneidels** [adamcoulombe/jquery.customSelect#3]
Hey Adam

thanks for this - looks great.

(I originally posted about IE9 not showing this properly on your demo page, but on my page its fine, so lets ignore that).

i have a <select> tage inside a hidden div.
when the div is opened - the width of that select is minute - almost un-noticable.
for now i have added a min-width on the span, but if you have better ideas i would appreciate it.

thanks!

**Comment by adamcoulombe** [comment]
best way to handle this is by calling .customSelect in your when you un-hide the div as opposed to just calling it on document.ready(). There is probably a way to build in detection for this but I'm thinking it will involve too much extra code. I would rather keep the plugin light. I am open to seeing solutions though if anyone knows of a quick fix for this.
