### ISSUE TITLE
Key events closes the options list

### ISSUE THREAD

**Issue by renatorodrigues** [adamcoulombe/jquery.customSelect#31]
After opening the options through a click, if you press some key, the list is closed automatically. This becomes a problem since it has a behavior different from the select default and prevents the user of switching between the options with the arrow keys.

**Comment by adamcoulombe** [comment]
I'm not seeing this problem. eg http://jsfiddle.net/adamco/gL8gk/ . Using arrow keys doesn't close the select

**Comment by adamcoulombe** [comment]
Please post which browser/environment you experience this issue with

**Comment by iSimonWeb** [comment]
Firefox has this issue. Chrome is ok.

**Comment by renatorodrigues** [comment]
Firefox, Opera and Internet Explorer. Chrome seems to be the only one working without problems.

**Comment by adamcoulombe** [comment]
Try latest version 0.3.5 There are some fixes that may address this

**Comment by iSimonWeb** [comment]
It works! Great! :)

**Comment by adamcoulombe** [comment]
Lol, sorry, I commited some broken code, it should work now

**Comment by renatorodrigues** [comment]
Working like a charm.
