### ISSUE TITLE
events fire twice

### ISSUE THREAD

**Issue by botaurus** [adamcoulombe/jquery.customSelect#32]
```
var ele = $('#selector_id').customSelect({customClass:'selector_style'});

ele.change(function(event, ele){
    console.log(event);//triggers twice
});
```

and .on('change', function (event) in the source triggers twice as well
any idea why? thanks!

**Comment by adamcoulombe** [comment]
Thanks. The last version invoked the change event on mouseup. I have changed it to call the function directly, so this shouldnt happen in 0.3.6, latest version

**Comment by botaurus** [comment]
much appreciated!
