### ISSUE TITLE
Adding options dynamically

### ISSUE THREAD

**Issue by Mathiu** [adamcoulombe/jquery.customSelect#41]
Hi, 

I have created empty select which is filled with options on page load event. And when i trigger customSelect on it, i am getting empty select without options. I found out that its issued by .trigger('update').

I am able to fix it by adding following code at the end of return function is your script:

``` javascript
var temp = $select.html();
$select.trigger('update');
$select.html(temp); 
```

but i am not sure if its a good fix. So please check it if you can.

**Comment by adamcoulombe** [comment]
There are two ways to do it. The best way is to append your options _then_ run `customSelect`:
http://jsfiddle.net/adamco/rvgZ3/

But sometimes you need to add options to a select that already has customSelect. In that case, you append your options, then trigger an update:

http://jsfiddle.net/adamco/v7Uzz/

**Comment by Mathiu** [comment]
Yeah, i know that, and i actually done it in one case, but in another one when i am not able to find function responsible for filling my select i can't use any of those methods, because first one is emptying my select because of trigger update and i can't use second one.

P.S. I have this problem in magento commerce and i really don't want to change any core js files which are filling my selects.

**Comment by adamcoulombe** [comment]
Not really familiar with magento. Ideally you would want to trigger the update inside a callback or event handler, so you could check the magento docs for that. Otherwise, you said it is working, but the only other suggestion I might say is you could poll to check when the content of the select changes.

``` html
<select id="myselect"></select>
```

_js_

``` javascript
var $select = $('#myselect');
function checkIfSelectHasBeenPopulated(){
    if($select.html().length<1){
        setTimeout(checkIfSelectHasBeenPopulated,300);
    }else{
        $select.trigger('update');
    }
}
checkIfSelectHasBeenPopulated();
```

**Comment by Mathiu** [comment]
Me neither. And that's why i'am struggling with it.  I will stay with my little fix.

Many thanks for your time and a great script :)
