### ISSUE TITLE
Specify width of SELECTs

### ISSUE THREAD

**Issue by NikitaKA** [adamcoulombe/jquery.customSelect#42]
There is a problem with customSelectSpan.outerWidth() on 95 line. It throw different values with same elements. So I need to specify default width.

![screen](https://f.cloud.github.com/assets/2543427/688049/66cb9c0e-da8c-11e2-9cf9-83ce493a9ac0.jpg)

How to do that? Maybe:

Initialization: 
$("#some-select").customSelect({width: 276});

Defaults:
var defaults = {
                    customClass: 'customSelect',
                    mapClass:    true,
                    mapStyle:    true,
                    width:       null
            },

On update:
$select.css({
                            '-webkit-appearance': 'menulist-button',
                            width:                options.width || customSelectSpan.outerWidth(),
                            position:             'absolute',
                            opacity:              0,
                            height:               selectBoxHeight,
                            fontSize:             customSelectSpan.css('font-size'),
                            left:                 position.left,
                            top:                  position.top
                        });

Thank you for your plugin! :)

**Comment by adamcoulombe** [comment]
Just specify a width in your CSS, as seen here:
http://jsfiddle.net/adamco/wNQTa/
