### ISSUE TITLE
Wrong position/width of span if the element is not visible

### ISSUE THREAD

**Issue by laantorchaweb** [adamcoulombe/jquery.customSelect#44]
I have two forms one is hidden (display:none) and only shows when you submit the first form (ajax).

I tried making something like this:

$(form).fadeIn(200, function(){
    $('.custom-select').trigger('update');
});

But doesn't update the width and the position of the select box.

I'll try to see what's going on.

BTW thanks for the plugin!

**Comment by markuspoerschke** [comment]
+1 

I will create a fix shortly.

**Comment by adamcoulombe** [comment]
Closing and moving conversation to pull request https://github.com/adamcoulombe/jquery.customSelect/pull/47
