### ISSUE TITLE
Long text overlaps with the button

### ISSUE THREAD

**Issue by marinagre** [adamcoulombe/jquery.customSelect#48]
I've attached a sample image

![image](https://f.cloud.github.com/assets/5087841/854532/a2719462-f507-11e2-8906-63f2caa1aad3.png)

**Comment by adamcoulombe** [comment]
That is because there is a width set on span.customSelect in the css styles. You can change that to however wide you want.

**Comment by marinagre** [comment]
I want it to be this wide. It should be trimming text to fit....

**Comment by adamcoulombe** [comment]
You can style it with overflow hidden and add an ellipsis with css, or style it however you want
http://jsfiddle.net/adamco/9vr8A/
