### ISSUE TITLE
100% select width

### ISSUE THREAD

**Issue by Tsimon-Dorakh** [adamcoulombe/jquery.customSelect#49]
Hi guys,

I have select width 100%, but during resize the window customSelect doesn't resize. May be I miss something, please help.

**Comment by adamcoulombe** [comment]
you need to trigger an update when you resize the window

```
$(window).resize(function(){
$('#mySelectBox').trigger('update');
});
```

That should work for you.... You may consider debouncing that if you notice performance issues.

**Comment by Tsimon-Dorakh** [comment]
Unfortunatelly your code doesn't work. I walked through lib code and realized that during customSelect init his width become absolute value and next update uses this absolute value.

**Comment by adamcoulombe** [comment]
Here is a working example.

http://jsfiddle.net/adamco/AB2Ch/

The key is to style the customSelect span. The select box will match the width of the customSelect span when you update it.

**Comment by Tsimon-Dorakh** [comment]
Ah, thanks a lot! I miss that span should be 100% width.
