### ISSUE TITLE
Bug on IE10

### ISSUE THREAD

**Issue by DrSchizo** [adamcoulombe/jquery.customSelect#56]
Thanks for this great plugin. I was previously using directy Ryan Fait's method, but it is much simpler with this script!

Unfortunately, while Custom Select works just fine on IE8 and IE9, it is a bit buggy on IE10 (as Ryan Fait's method), even on the demo on the officiel website (http://adam.co/lab/jquery/customselect/). The select list doesn't show up at the bottom of the select box.

Thank you!

**Comment by pdamer** [comment]
The position of the options is also off in Safari 6.0.5

**Comment by adamcoulombe** [comment]
This is the behavior of how select boxes are positioned natively in those browsers. So it's not really a bug, it's just how the browser happens to display select boxes. Because it functions otherwise as expected I'm going to close this issue.
