### ISSUE TITLE
Broken on Magento

### ISSUE THREAD

**Issue by tehn2310** [adamcoulombe/jquery.customSelect#59]
Hi

There is some issue with Prototype used in Magento. Event 'update' crash display select. When I change 'update' to 'update2' it's work fine. But I thing it's not a good solution :)

**Comment by franksmule** [comment]
Facing the same problem, changing update to something else makes it work fine

**Comment by joeyhoer** [comment]
I can also confirm this bug. I renamed the `update` event to `updateCustomSelect`, and that worked well.

**Comment by adamcoulombe** [comment]
jQuery lets you [namespace events](http://api.jquery.com/event.namespace/). If somebody wants to make such a change, I will merge it.

**Comment by joeyhoer** [comment]
This is not an issue with Magento, per se, but a compatibility issue with Prototype.js which is required for the current version of Magento.

http://prototypejs.org/doc/latest/dom/Element/update/

I've submitted a pull request that resolves the issue, and namespaces events, which is good practice.

**Comment by adamcoulombe** [comment]
Please update to latest version and try again. Events are now namespaced so the issue should be fixed. Thanks @joeyhoer
