### ISSUE TITLE
Opening native select menus on mobile

### ISSUE THREAD

**Issue by shantp** [adamcoulombe/jquery.customSelect#6]
In mobile Safari on the iPhone the native select menu opens as expected when clicking the customSelect. However, clicking does nothing in Chrome on Android and the default Android browser.

**Comment by adamcoulombe** [comment]
Thanks for reporting.. What version of android are you running? I only have an emulator running jellybean but it appears to work fine in the default browser... does the [demo provided](http://adam.co/lab/jquery/customselect/demo) and/or the demo on the [customSelect webpage](http://adam.co/lab/jquery/customselect/) not work either? I'll do my best to resolve this, in the mean time if you can provide any details or if you come up with a solution please post back

**Comment by shantp** [comment]
Thanks for the quick response. Both demos work on my Android so this appears to be an issue in my setup. I will investigate further and reply when I find the cause.

**Comment by adamcoulombe** [comment]
Android browsers should have a javascript/debug console... check to make sure there are no other javascript errors on your page that could be causing javascript to fail.

**Comment by shantp** [comment]
I know this update has taken a while, but just wanted to let you know that I am still having issues getting the native Android to open. Remote debugging is showing no js errors from Android Chrome and the customSelect is there and styleable, but touching it does nothing. I have the customSelect inside of an iscroll4 div, which may be interfering. Thoughts?

**Comment by shantp** [comment]
Once the select is removed from inside the iscroll4 wrapper it works so I think I've found my issue.
