### ISSUE TITLE
Problem when i apply "multiple" attribute to the select.

### ISSUE THREAD

**Issue by vipul2012** [adamcoulombe/jquery.customSelect#68]
Hi,

First of all thanks for the great plugin. Your select box works great in desktop and mobile but i have a small problem. When i apply  "multiple" attribute to select box, it's stop working. Any idea to manage your plugin with "multiple" attribute enabled. You can check below demo link.

http://jsfiddle.net/hysHB/776/

Any help greatly appreciated.

Thanks.

**Comment by Doc87** [comment]
Hi, 

I have the same problem when apply the multiselection to the select box. @vipul2012 Were you able to fix it?

**Comment by adamcoulombe** [comment]
Hi... This plugin is not intended to work with a "multiple" select. They  are fundamentally different in the way they operate, and unfortunately the technique used in this plugin is somewhat of a hack that just wouldn't work. There are other plugins out there that would do what you need though...
