### ISSUE TITLE
Set option value does not work

### ISSUE THREAD

**Issue by martin1919** [adamcoulombe/jquery.customSelect#78]
Hello,

I have a problem with dropdown list with customSelect.
When I call
$('#select_id').val('optionValue');
the selected option is not visible.
There is an example
http://jsfiddle.net/7ttWj/520/

I have also tried ".trigger('update');", but does not work, as well.

Can you help with that?
Thanks in advance

**Comment by ft-harai** [comment]
Hi. This code might help you:

<pre>
var $cs = $('.styled').customSelect();
$cs.val('three').trigger('render');
</pre>

You can see this changes in version 0.5.0:
https://github.com/adamcoulombe/jquery.customSelect/commit/288599bdafddd953eaae3a97dbe9761e6e635b89

**Comment by martin1919** [comment]
Thank you, this solved my problem
