### ISSUE TITLE
Width to 100% not working

### ISSUE THREAD

**Issue by cookiekitty** [adamcoulombe/jquery.customSelect#91]
Setting the Width to 100% will cause the entire dropdown to become oversized as compared to it's parent.

I'm trying to do a responsive website design and I need the dropdowns to be 100% of whatever div they're living in. I don't want to have to write a script to determine the size of the parent just to set the size of the dropdown when 100% should work.

As seen here: http://jsfiddle.net/wNQTa/6/

**Comment by juanfernandes** [comment]
I'm having the same issue. Im also using the matchmedia queries as suggested but it still does not work. Why was this issue closed without comment?

**Comment by cookiekitty** [comment]
I found another issue about 100% width where he replied that his mod is not
for use with responsive design, so I kinda gave up on it.

**Comment by emiliemarchand** [comment]
Try setting `box-sizing: border-box;` (You may need to adjust the height if you set one)
